//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITR.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CITR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;project xmlns=&quot;http://www.plcopen.org/xml/tc6_0200&quot;&gt;
        ///  &lt;fileHeader companyName=&quot;Prosoft - Systems&quot; productName=&quot;Epsilon LD&quot; productVersion=&quot;Epsilon LD V1.6.14.0&quot; creationDateTime=&quot;2021-05-11T13:17:08.4399755&quot; /&gt;
        ///  &lt;contentHeader name=&quot;Без имени12.project&quot; modificationDateTime=&quot;2021-05-11T13:16:29.1096554&quot;&gt;
        ///    &lt;coordinateInfo&gt;
        ///      &lt;fbd&gt;
        ///        &lt;scaling x=&quot;1&quot; y=&quot;1&quot; /&gt;
        ///      &lt;/fbd&gt;
        ///      &lt;ld&gt;
        ///        &lt;scaling x=&quot;1&quot; y=&quot;1&quot; /&gt;
        ///      &lt;/ld&gt;
        ///      &lt;sfc&gt;
        ///        [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Application_SHB {
            get {
                return ResourceManager.GetString("Application_SHB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;project xmlns=&quot;http://www.plcopen.org/xml/tc6_0200&quot;&gt;
        ///  &lt;fileHeader companyName=&quot;Prosoft - Systems&quot; productName=&quot;Epsilon LD&quot; productVersion=&quot;Epsilon LD V1.6.14.0&quot; creationDateTime=&quot;2021-06-24T17:45:05.8483292&quot; /&gt;
        ///  &lt;contentHeader name=&quot;USO1.project&quot; modificationDateTime=&quot;2021-06-24T17:44:30.8891239&quot;&gt;
        ///    &lt;coordinateInfo&gt;
        ///      &lt;fbd&gt;
        ///        &lt;scaling x=&quot;1&quot; y=&quot;1&quot; /&gt;
        ///      &lt;/fbd&gt;
        ///      &lt;ld&gt;
        ///        &lt;scaling x=&quot;1&quot; y=&quot;1&quot; /&gt;
        ///      &lt;/ld&gt;
        ///      &lt;sfc&gt;
        ///        &lt;scali [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string DEV_SHB {
            get {
                return ResourceManager.GetString("DEV_SHB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] exel_SHB {
            get {
                object obj = ResourceManager.GetObject("exel_SHB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;project&gt;
        ///  &lt;fileHeader companyName=&quot;Prosoft - Systems&quot; productName=&quot;Epsilon LD&quot; productVersion=&quot;Epsilon LD V1.6.14.0&quot; creationDateTime=&quot;2020-09-17T16:24:44.2616532&quot; /&gt;
        ///  &lt;contentHeader name=&quot;test.project&quot; modificationDateTime=&quot;2020-09-17T16:24:28.6739196&quot;&gt;
        ///    &lt;coordinateInfo&gt;
        ///      &lt;fbd&gt;
        ///        &lt;scaling x=&quot;1&quot; y=&quot;1&quot; /&gt;
        ///      &lt;/fbd&gt;
        ///      &lt;ld&gt;
        ///        &lt;scaling x=&quot;1&quot; y=&quot;1&quot; /&gt;
        ///      &lt;/ld&gt;
        ///      &lt;sfc&gt;
        ///        &lt;scaling x=&quot;1&quot; y=&quot;1&quot; /&gt;
        ///      &lt;/sfc&gt;
        ///    &lt;/coord [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GVL_SHB {
            get {
                return ResourceManager.GetString("GVL_SHB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_ico {
            get {
                object obj = ResourceManager.GetObject("help_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] help_vu {
            get {
                object obj = ResourceManager.GetObject("help_vu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon ITR {
            get {
                object obj = ResourceManager.GetObject("ITR", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
